/**
 * Multi-Style HTML Report Generator
 * P2-F1: 支持 5 种专业视觉风格 + 自定义风格
 *
 * Styles:
 * - sports: 体育风格 - Dynamic, energetic, bold
 * - entertainment: 娱乐风格 - Vibrant, colorful, playful
 * - finance: 财经风格 - Professional, clean, data-focused
 * - politics: 政治风格 - Formal, authoritative, serious
 * - military: 军事风格 - Strong, disciplined, structured
 */

const fs = require('fs');
const path = require('path');

// Built-in style definitions
const BUILT_IN_STYLES = {
  sports: {
    name: '体育风格',
    primary: '#FF6B35',
    secondary: '#004E89',
    accent: '#F7C548',
    background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    cardBg: '#1f2937',
    text: '#F3F4F6',
    textMuted: '#9CA3AF',
    border: '#FF6B35',
    headerGradient: 'linear-gradient(135deg, #FF6B35 0%, #F7C548 100%)',
    fontFamily: "'Impact', 'Arial Black', sans-serif",
    articleFont: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  },
  entertainment: {
    name: '娱乐风格',
    primary: '#FF1493',
    secondary: '#9400D3',
    accent: '#00CED1',
    background: 'linear-gradient(135deg, #2d1b4e 0%, #1a0a2e 100%)',
    cardBg: '#3d2366',
    text: '#FFFFFF',
    textMuted: '#E0B0FF',
    border: '#FF1493',
    headerGradient: 'linear-gradient(135deg, #FF1493 0%, #9400D3 50%, #00CED1 100%)',
    fontFamily: "'Comic Sans MS', 'Chalkboard SE', sans-serif",
    articleFont: "'Georgia', serif"
  },
  finance: {
    name: '财经风格',
    primary: '#0D47A1',
    secondary: '#1565C0',
    accent: '#00C853',
    background: 'linear-gradient(180deg, #FAFAFA 0%, #ECEFF1 100%)',
    cardBg: '#FFFFFF',
    text: '#263238',
    textMuted: '#607D8B',
    border: '#0D47A1',
    headerGradient: 'linear-gradient(135deg, #0D47A1 0%, #1565C0 100%)',
    fontFamily: "'Arial', 'Helvetica', sans-serif",
    articleFont: "'Times New Roman', Georgia, serif"
  },
  politics: {
    name: '政治风格',
    primary: '#8B0000',
    secondary: '#1A1A2E',
    accent: '#C9A227',
    background: 'linear-gradient(180deg, #F5F5F5 0%, #E8E8E8 100%)',
    cardBg: '#FFFFFF',
    text: '#2C2C2C',
    textMuted: '#666666',
    border: '#8B0000',
    headerGradient: 'linear-gradient(135deg, #8B0000 0%, #1A1A2E 100%)',
    fontFamily: "'Times New Roman', Georgia, serif",
    articleFont: "'Georgia', serif"
  },
  military: {
    name: '军事风格',
    primary: '#2E5A1C',
    secondary: '#4A5D23',
    accent: '#C4B538',
    background: 'linear-gradient(180deg, #1a1f16 0%, #2d3425 100%)',
    cardBg: '#232b1e',
    text: '#E8E6D9',
    textMuted: '#A8A695',
    border: '#C4B538',
    headerGradient: 'linear-gradient(135deg, #2E5A1C 0%, #4A5D23 50%, #C4B538 100%)',
    fontFamily: "'Courier New', monospace",
    articleFont: "'Arial', sans-serif"
  }
};

class ReportGenerator {
  constructor(options = {}) {
    this.style = options.style || 'finance';
    this.customStyle = options.customStyle || null;
    this.title = options.title || 'Report';
    this.subtitle = options.subtitle || '';
    this.author = options.author || 'UI-TARS';
    this.dateFormat = options.dateFormat || 'YYYY-MM-DD';

    // Get style config
    this.styleConfig = this._getStyleConfig();
  }

  /**
   * Get style configuration
   */
  _getStyleConfig() {
    if (this.customStyle) {
      return { ...BUILT_IN_STYLES.finance, ...this.customStyle };
    }
    return BUILT_IN_STYLES[this.style] || BUILT_IN_STYLES.finance;
  }

  /**
   * Generate complete HTML report
   */
  generate(data) {
    const style = this.styleConfig;
    const sections = this._generateSections(data);
    const date = this._formatDate(new Date());

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${this.title}</title>
    <style>
        ${this._generateCSS(style)}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>${this.title}</h1>
            ${this.subtitle ? `<p>${this.subtitle}</p>` : ''}
            <div class="meta">
                <span>${style.name}</span>
                <span>•</span>
                <span>${date}</span>
                <span>•</span>
                <span>${this.author}</span>
            </div>
        </header>

        <main class="content">
            ${sections}
        </main>

        <footer class="footer">
            <p>Generated by UI-TARS Report Generator</p>
        </footer>
    </div>
</body>
</html>`;
  }

  /**
   * Generate CSS based on style
   */
  _generateCSS(style) {
    return `
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: ${style.articleFont};
            background: ${style.background};
            color: ${style.text};
            min-height: 100vh;
            padding: 20px;
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: ${style.cardBg};
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);
            overflow: hidden;
        }

        .header {
            background: ${style.headerGradient};
            color: white;
            padding: 60px 40px;
            text-align: center;
            position: relative;
            overflow: hidden;
        }

        .header::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="none" stroke="rgba(255,255,255,0.1)" stroke-width="0.5"/></svg>');
            background-size: 100px 100px;
            opacity: 0.5;
        }

        .header h1 {
            font-family: ${style.fontFamily};
            font-size: 2.8em;
            margin-bottom: 15px;
            font-weight: 700;
            position: relative;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }

        .header p {
            font-size: 1.3em;
            opacity: 0.95;
            position: relative;
            font-weight: 300;
        }

        .header .meta {
            margin-top: 25px;
            font-size: 0.9em;
            opacity: 0.85;
            position: relative;
            display: flex;
            justify-content: center;
            gap: 15px;
        }

        .content {
            padding: 50px 40px;
        }

        .section {
            margin-bottom: 50px;
            padding: 30px;
            background: rgba(255,255,255,0.03);
            border-radius: 10px;
            border-left: 4px solid ${style.border};
        }

        .section h2 {
            color: ${style.primary};
            font-size: 2em;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid ${style.border};
            font-family: ${style.fontFamily};
        }

        .subsection {
            margin-bottom: 25px;
        }

        .subsection h3 {
            color: ${style.accent};
            font-size: 1.4em;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
        }

        .subsection h3::before {
            content: '';
            width: 8px;
            height: 8px;
            background: ${style.border};
            margin-right: 12px;
            border-radius: 2px;
            transform: rotate(45deg);
        }

        .card-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 25px;
            margin-top: 25px;
        }

        .card {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            padding: 25px;
            border-radius: 10px;
            transition: all 0.3s ease;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
            border-color: ${style.border};
        }

        .card h4 {
            color: ${style.primary};
            font-size: 1.3em;
            margin-bottom: 15px;
            font-family: ${style.fontFamily};
        }

        .card p {
            color: ${style.textMuted};
            line-height: 1.7;
        }

        .stat-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 25px;
        }

        .stat-card {
            background: ${style.primary};
            color: white;
            padding: 30px;
            border-radius: 12px;
            text-align: center;
            position: relative;
            overflow: hidden;
        }

        .stat-card::after {
            content: '';
            position: absolute;
            top: -50%;
            right: -50%;
            width: 100%;
            height: 100%;
            background: radial-gradient(circle, rgba(255,255,255,0.2) 0%, transparent 70%);
        }

        .stat-value {
            font-size: 3em;
            font-weight: 700;
            font-family: ${style.fontFamily};
        }

        .stat-label {
            font-size: 1em;
            opacity: 0.9;
            margin-top: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
            background: rgba(255,255,255,0.02);
            border-radius: 8px;
            overflow: hidden;
        }

        th {
            background: ${style.primary};
            color: white;
            padding: 15px;
            text-align: left;
            font-family: ${style.fontFamily};
        }

        td {
            padding: 15px;
            border-bottom: 1px solid rgba(255,255,255,0.1);
            color: ${style.textMuted};
        }

        tr:hover td {
            background: rgba(255,255,255,0.05);
        }

        .tag {
            display: inline-block;
            padding: 5px 15px;
            background: ${style.accent};
            color: ${style.background};
            border-radius: 20px;
            font-size: 0.85em;
            margin-right: 8px;
            margin-bottom: 8px;
        }

        .highlight {
            background: linear-gradient(120deg, ${style.primary}22, ${style.accent}22);
            padding: 2px 8px;
            border-radius: 4px;
        }

        .footer {
            background: rgba(0,0,0,0.2);
            padding: 25px;
            text-align: center;
            color: ${style.textMuted};
            font-size: 0.9em;
        }

        @media (max-width: 768px) {
            .header {
                padding: 40px 20px;
            }

            .header h1 {
                font-size: 2em;
            }

            .content {
                padding: 30px 20px;
            }

            .card-grid, .stat-grid {
                grid-template-columns: 1fr;
            }
        }
    `;
  }

  /**
   * Generate sections from data
   */
  _generateSections(data) {
    if (!data || !data.sections) {
      return this._generateDefaultSection(data);
    }

    return data.sections.map(section => this._generateSection(section)).join('\n');
  }

  /**
   * Generate a single section
   */
  _generateSection(section) {
    const hasSubsections = section.subsections && section.subsections.length > 0;
    const hasCards = section.cards && section.cards.length > 0;
    const hasStats = section.stats && section.stats.length > 0;
    const hasTable = section.table;
    const hasTags = section.tags && section.tags.length > 0;
    const hasList = section.list && section.list.length > 0;

    return `
        <section class="section">
            <h2>${section.title}</h2>
            ${section.description ? `<p style="color: ${this.styleConfig.textMuted}; margin-bottom: 25px;">${section.description}</p>` : ''}

            ${hasTags ? `
            <div class="tags" style="margin-bottom: 25px;">
                ${section.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
            </div>
            ` : ''}

            ${hasSubsections ? section.subsections.map(sub => `
                <div class="subsection">
                    <h3>${sub.title}</h3>
                    <p>${sub.content}</p>
                </div>
            `).join('') : ''}

            ${hasCards ? `
            <div class="card-grid">
                ${section.cards.map(card => `
                    <div class="card">
                        <h4>${card.title}</h4>
                        <p>${card.content}</p>
                    </div>
                `).join('')}
            </div>
            ` : ''}

            ${hasStats ? `
            <div class="stat-grid">
                ${section.stats.map(stat => `
                    <div class="stat-card">
                        <div class="stat-value">${stat.value}</div>
                        <div class="stat-label">${stat.label}</div>
                    </div>
                `).join('')}
            </div>
            ` : ''}

            ${hasTable ? `
            <table>
                <thead>
                    <tr>
                        ${section.table.headers.map(h => `<th>${h}</th>`).join('')}
                    </tr>
                </thead>
                <tbody>
                    ${section.table.rows.map(row => `
                        <tr>
                            ${row.map(cell => `<td>${cell}</td>`).join('')}
                        </tr>
                    `).join('')}
                </tbody>
            </table>
            ` : ''}

            ${hasList ? `
            <ul style="list-style: none; padding-left: 0;">
                ${section.list.map(item => `
                    <li style="padding: 10px 0; border-bottom: 1px solid rgba(255,255,255,0.1); color: ${this.styleConfig.textMuted};">
                        <span style="color: ${this.styleConfig.border}; margin-right: 10px;">▸</span>${item}
                    </li>
                `).join('')}
            </ul>
            ` : ''}
        </section>
    `;
  }

  /**
   * Generate default section if no data provided
   */
  _generateDefaultSection(data) {
    return `
        <section class="section">
            <h2>报告内容</h2>
            <p style="color: ${this.styleConfig.textMuted};">
                ${typeof data === 'string' ? data : '暂无内容'}
            </p>
        </section>
    `;
  }

  /**
   * Format date
   */
  _formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  /**
   * Save report to file
   */
  async save(data, outputPath) {
    const html = this.generate(data);
    const dir = path.dirname(outputPath);

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, html, 'utf-8');
    return outputPath;
  }

  /**
   * Get available styles
   */
  static getAvailableStyles() {
    return Object.keys(BUILT_IN_STYLES).map(key => ({
      id: key,
      name: BUILT_IN_STYLES[key].name
    }));
  }

  /**
   * Create report generator with specified style
   */
  static create(style, options = {}) {
    return new ReportGenerator({ ...options, style });
  }

  /**
   * Create report generator with custom style
   */
  static createWithCustomStyle(customStyle, options = {}) {
    return new ReportGenerator({ ...options, customStyle });
  }
}

module.exports = ReportGenerator;
module.exports.BUILT_IN_STYLES = BUILT_IN_STYLES;
